Add required deps to project (#33)
* The project needs pyspark and delta-spark not just in dev mode, also in regular installs. Otherwise you get an error like ImportError: cannot import name 'configure_spark_with_delta_pip' from 'delta' (/home/holden/miniconda3/lib/python3.10/site-packages/delta/__init__.py)

* We also need requests.